[2024-12-11 23:20:15,743] ERROR log_exception() L1449 Exception on /historico [POST] - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1800, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1076, in _init_compiled
    param = [
            ^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1077, in <listcomp>
    processors[key](compiled_params[key])
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1003, in process
    raise TypeError(
TypeError: SQLite DateTime type only accepts Python datetime and date objects as input.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py", line 145, in add_historico
    session.commit()
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 1451, in commit
    self._transaction.commit(_to_root=self.future)
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 3386, in flush
    self._flush(objects)
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 3525, in _flush
    with util.safe_reraise():
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 3486, in _flush
    flush_context.execute()
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1238, in _emit_insert_statements
    result = connection._execute_20(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\sql\elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1806, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1800, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1076, in _init_compiled
    param = [
            ^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 1077, in <listcomp>
    processors[key](compiled_params[key])
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1003, in process
    raise TypeError(
sqlalchemy.exc.StatementError: (builtins.TypeError) SQLite DateTime type only accepts Python datetime and date objects as input.
[SQL: INSERT INTO historico (descricao, data_insercao, projeto_id) VALUES (?, ?, ?)]
[parameters: [{'data_insercao': '11/12/2024 23:20 ', 'descricao': 'csfcsd', 'projeto_id': '8'}]]
[2024-12-11 23:20:15,852] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 23:20:15] "[35m[1mPOST /historico HTTP/1.1[0m" 500 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 23:23:05,665] WARNING _log() L225   * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment. - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 23:23:05,665] INFO _log() L225   * Running on http://192.168.3.46:5000/ (Press CTRL+C to quit) - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 23:23:10,078] INFO listar_projetos() L83   Listagem de projetos realizada com sucesso. - call_trace=C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py L83  
[2024-12-11 23:23:10,079] INFO listar_projetos() L88   6Projetos encontrado: - call_trace=C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py L88  
[2024-12-11 23:23:10,087] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 23:23:10] "GET /projetos HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 23:23:12,328] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 23:23:12] "OPTIONS /historico HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 23:23:12,341] INFO listar_historico() L190  Listagem de histórico do projeto ID 8 realizada com sucesso. - call_trace=C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py L190 
[2024-12-11 23:23:12,343] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 23:23:12] "GET /historico HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 23:23:44,822] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 23:23:44] "OPTIONS /historico HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
